spring:
  main:
    banner-mode: "off"
    log-startup-info: false
  application:
    name: sip-mf-simulator-backend



  datasource:
    url: jdbc:postgresql://ep-lingering-resonance-at33bntp.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
#    url: jdbc:postgresql://localhost:5432/sipMfSimulatorDB
    username: neondb_owner
    password: npg_vh1g2PktBHAN
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    # Quiet down Spring's core startup and web routing logs
    org.springframework: WARN

    # Quiet down HikariCP database connection pool logs
    com.zaxxer.hikari: WARN

    # Quiet down Hibernate engine initialization logs
    org.hibernate: WARN

    # Keep your own code talking at INFO level
    com.example.employeeonboardingworkflowengine: INFO
